//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPSWebApplication.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APPUser()
        {
            this.APPUserProfiles = new HashSet<APPUserProfile>();
        }
    
        public string UHCLEmail { get; set; }
        public string UHCLEmailPassword { get; set; }
        public string UserRole { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPUserProfile> APPUserProfiles { get; set; }
    }
}
