//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPSWebApplication.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPUserProfile
    {
        public int UHCLID { get; set; }
        public string UHCLIDPassword { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ContactNumber { get; set; }
        public string UHCLEmail { get; set; }
        public string UHCLEmailPassword { get; set; }
        public string UserAddress { get; set; }
    
        public virtual APPUser APPUser { get; set; }
    }
}
