//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPSWebApplication.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog16_17
    {
        public string Course { get; set; }
        public string SWEN { get; set; }
        public string CSCI { get; set; }
        public string SENG { get; set; }
        public string Subject { get; set; }
        public string Catalog { get; set; }
        public string LongTitle { get; set; }
        public string creditHrs { get; set; }
    }
}
