//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPSWebApplication.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMST_Courses
    {
        public string Course { get; set; }
        public string CourseName { get; set; }
        public string CourseLevel { get; set; }
        public Nullable<int> CreditHrs { get; set; }
        public string UnderSpecialization { get; set; }
    }
}
