//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPSWebApplication.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetail
    {
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string studentID { get; set; }
        public string UHCLEmail { get; set; }
        public string admittedSemester { get; set; }
        public string currentSemester { get; set; }
        public string majorName { get; set; }
        public string CGPA { get; set; }
        public string enrolledCoursesAndSemesters { get; set; }
        public string completedCoursesAndGrades { get; set; }
        public string ProgramCompletionType { get; set; }
        public string AssignedFoundation { get; set; }
    }
}
